/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service liveness probe
     * @description Lightweight liveness check used by the web app's home page. Returns the service identity and a greeting. For operational health checks prefer the actuator endpoint (`/actuator/health`).
     */
    get: operations['ping'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Service identity and greeting. */
    PingResponse: {
      /**
       * @description Service identifier.
       * @example fikaliako-api
       */
      service: string;
      /**
       * @description Human greeting, in Malagasy.
       * @example Aiza no hisakafo androany ?
       */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is up. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "service": "fikaliako-api",
           *       "message": "Aiza no hisakafo androany ?"
           *     }
           */
          'application/json': components['schemas']['PingResponse'];
        };
      };
    };
  };
}
