/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service liveness probe
     * @description Lightweight liveness check used by the web app's home page. Returns the service identity and a greeting. For operational health checks prefer the actuator endpoint (`/actuator/health`).
     */
    get: operations['ping'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account
     * @description Creates a phone-number account (project book ch. 4.7). `account_type` picks the role: `consumer` (default) or `business` (premium establishment account — managing an establishment additionally requires an admin-granted link). The password is hashed with Argon2id and a 6-digit verification code is sent by SMS; the account cannot log in until `/v1/auth/verify-phone` succeeds.
     */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/verify-phone': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify the phone number with the SMS code
     * @description Consumes the 6-digit code (10-minute lifetime, 5 attempts) and opens the first session. Whether a number is registered is never revealed: an unknown number answers the same 400 as a bad code.
     */
    post: operations['verifyPhone'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/resend-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Re-send the verification code
     * @description Always answers 202 so account existence is not revealed. Issuance is capped at 5 codes/hour/number (book ch. 7.3).
     */
    post: operations['resendOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in with phone number and password
     * @description Opens a session: a 15-minute access JWT plus a 30-day single-use refresh token. Unverified phones get a 403 pointing at `/v1/auth/verify-phone`; suspended accounts get a 403 too.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the refresh token
     * @description Exchanges a live refresh token for a fresh access JWT and a new refresh token. Each refresh token is single-use: presenting an already-rotated one is treated as theft and revokes the whole session family.
     */
    post: operations['refreshTokens'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log out (revoke the session)
     * @description Revokes the session the refresh token belongs to, server-side and idempotently. The current access token stays valid for its remaining lifetime (≤ 15 min) — clients should also drop it locally.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password-reset code
     * @description Sends a reset code by SMS if the number has an account. Always answers 202 so account existence is not revealed; issuance shares the 5/hour/number cap.
     */
    post: operations['forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset the password with the SMS code
     * @description Sets a new password after validating the reset code, then revokes every live session of the account (the reset proves control of the number, not of every device).
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change the password (authenticated)
     * @description Requires the current password. Every other session is revoked and a fresh token pair is returned so the calling device stays logged in.
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/nearby': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Establishments near a point, cheapest first
     * @description The core discovery query (project book ch. 6.2): active establishments within `radius` metres of (`lat`, `lng`), ordered cheapest first then by distance. Uses `ST_DWithin` on the GiST index; target < 300 ms p95. The result set is bounded by `radius` and `limit`, so it is **not** cursor-paginated (`next_cursor` is always absent).
     */
    get: operations['nearby'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Typo-tolerant text and smart search
     * @description Free-text discovery over names, districts, cities, cuisine labels and dish words, with FR/MG synonym expansion — searching `romazava` also surfaces Malagasy-cuisine establishments whose name never mentions the dish (project book ch. 4.2). Typo tolerance runs on PostgreSQL trigram similarity behind a port, so the target Meilisearch engine (ch. 7.1) can replace it without an API change. Deterministic smart rules first turn natural-language phrases into filters: "j'ai faim" becomes open-now within 1 km ranked by the ch. 4.2 discovery score (Bayesian note + recent reviews + budget adequacy), "pizza pas cher" keeps searching "pizza" under 5 000 Ar. What was applied is echoed in `interpretation`; explicit query parameters always win over interpreted ones. Results are relevance-ordered (or discovery-scored for filter-only smart queries); `next_cursor` carries an offset. All `/v1/nearby` filters combine, and an optional (`lat`, `lng`) pair annotates each hit with `distance_m` and unlocks `radius` narrowing — search anywhere on the map, not only around the user (ch. 4.1).
     */
    get: operations['search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rankings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catalog of thematic tops
     * @description The shareable thematic tops of project book ch. 4.6: best rated, best gargottes, best value for money, monthly revelations, plus one top per cuisine of the referential. Orderings read the Bayesian note the nightly aggregation computes, so tops move once a day.
     */
    get: operations['listRankings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rankings/{topicId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One thematic top
     * @description Up to 20 establishments for a topic from the catalog (e.g. `top-rated`, `best-gargottes`, `best-value`, `revelations`, `cuisine-malagasy`). Entry requires at least 3 reviews (1 for revelations, which also must have been added within the last 30 days); the ordering key is the volume-damped Bayesian note (ch. 4.6).
     */
    get: operations['getRanking'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/establishments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse establishments
     * @description Active establishments, newest first, cursor-paginated. Filters combine (project book ch. 4.3).
     */
    get: operations['listEstablishments'];
    put?: never;
    /**
     * Propose a new establishment
     * @description Community contribution (project book ch. 4.8) — anyone connected can propose a new establishment, positioned by dropping a pin (formal addresses are rare). Nothing is published directly: the proposal is stored as a `create` contribution in the moderation queue and becomes an establishment once a moderator applies it.
     */
    post: operations['proposeEstablishment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/establishments/{idOrSlug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Establishment detail
     * @description Full detail for one establishment, resolvable by UUID or SEO slug (the slug path powers Google-indexable pages — project book ch. 11.3). `open_now` is computed server-side in Indian/Antananarivo.
     */
    get: operations['getEstablishment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/establishments/{establishmentId}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Reviews for an establishment
     * @description Published reviews, newest first, cursor-paginated.
     */
    get: operations['listReviews'];
    put?: never;
    /**
     * Post a review
     * @description One review per user per establishment, scored 1–5 on five criteria (project book ch. 4.4). The global note is the weighted mean with quality counted twice. A second review from the same account is a 409.
     */
    post: operations['createReview'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current authenticated user */
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update the profile
     * @description Partial update — absent fields stay untouched.
     */
    patch: operations['updateCurrentUser'];
    trace?: never;
  };
  '/v1/users/me/favorites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The user's favorites
     * @description Favorited establishments, most recently added first, cursor-paginated (project book ch. 4.6).
     */
    get: operations['listFavorites'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me/favorites/{establishmentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Add a favorite
     * @description Idempotent add to the user's favorites (project book ch. 4.6).
     */
    put: operations['addFavorite'];
    post?: never;
    /**
     * Remove a favorite
     * @description Idempotent removal from the user's favorites.
     */
    delete: operations['removeFavorite'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/business/establishments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Establishments managed by this account
     * @description The establishments an admin granted this `business` account. One page, no cursor — an account manages a handful at most.
     */
    get: operations['listManagedEstablishments'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/business/establishments/{establishmentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update the business profile
     * @description Partial update of an establishment this account manages: contact fields, average price, amenities, and `active`/`closed` status. Position changes go through the community loop (book ch. 4.8) and `verified` is a moderator act — neither is editable here. Admins pass the ownership check.
     */
    patch: operations['updateManagedEstablishment'];
    trace?: never;
  };
  '/v1/business/establishments/{establishmentId}/opening-hours': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Replace the opening hours
     * @description Full replacement of the opening intervals (multiple per day allowed, day 0 = Monday — book ch. 6.1).
     */
    put: operations['replaceOpeningHours'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/establishments/{establishmentId}/managers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Managers of an establishment */
    get: operations['listEstablishmentManagers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/establishments/{establishmentId}/managers/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Grant management of an establishment
     * @description Links a `business` account to the establishment. Idempotent; every effective grant lands in the immutable audit log (book ch. 7.3). Granting to a non-business account is a 400.
     */
    put: operations['grantEstablishmentManager'];
    post?: never;
    /**
     * Revoke management of an establishment
     * @description Idempotent; effective revocations are audit-logged.
     */
    delete: operations['revokeEstablishmentManager'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Service identity and greeting. */
    PingResponse: {
      /**
       * @description Service identifier.
       * @example fikaliako-api
       */
      service: string;
      /**
       * @description Human greeting, in Malagasy.
       * @example Aiza no hisakafo androany ?
       */
      message: string;
    };
    /** @description RFC 9457 problem detail. */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string;
      /** @example Not found */
      title: string;
      /** @example 404 */
      status: number;
      /** @example Establishment 'nope' not found. */
      detail?: string;
      /** @example /v1/establishments/nope */
      instance?: string;
      /** @description Echoes the `X-Correlation-Id` response header. */
      correlation_id?: string;
    };
    /**
     * @description E.164 phone number — the account identifier (book ch. 4.7).
     * @example +261340000001
     */
    PhoneNumber: string;
    /**
     * @description 6-digit one-time code received by SMS.
     * @example 123456
     */
    OtpCode: string;
    /**
     * @description Account role: `user` = consumer, `business` = premium establishment account, `moderator` and `admin` = back-office.
     * @enum {string}
     */
    UserRole: 'user' | 'business' | 'moderator' | 'admin';
    /** @description The account as its owner sees it. */
    UserProfile: {
      /** Format: uuid */
      id: string;
      phone: components['schemas']['PhoneNumber'];
      /** @example Naina */
      display_name: string;
      role: components['schemas']['UserRole'];
      phone_verified: boolean;
      /** @enum {string} */
      locale: 'fr' | 'mg';
      /** Format: date-time */
      created_at: string;
    };
    RegisterRequest: {
      phone: components['schemas']['PhoneNumber'];
      password: string;
      display_name: string;
      /**
       * @description `consumer` (default) or `business` — a premium establishment account (restaurant, gargotte, café…).
       * @default consumer
       * @enum {string}
       */
      account_type: 'consumer' | 'business';
      /**
       * @default fr
       * @enum {string}
       */
      locale: 'fr' | 'mg';
    };
    VerifyPhoneRequest: {
      phone: components['schemas']['PhoneNumber'];
      code: components['schemas']['OtpCode'];
    };
    ResendOtpRequest: {
      phone: components['schemas']['PhoneNumber'];
    };
    LoginRequest: {
      phone: components['schemas']['PhoneNumber'];
      password: string;
    };
    RefreshRequest: {
      refresh_token: string;
    };
    LogoutRequest: {
      refresh_token: string;
    };
    ForgotPasswordRequest: {
      phone: components['schemas']['PhoneNumber'];
    };
    ResetPasswordRequest: {
      phone: components['schemas']['PhoneNumber'];
      code: components['schemas']['OtpCode'];
      new_password: string;
    };
    ChangePasswordRequest: {
      current_password: string;
      new_password: string;
    };
    /** @description A session: short-lived access JWT plus the single-use refresh token (book ch. 7.3). Store the refresh token securely — it is shown once. */
    AuthTokens: {
      /** @enum {string} */
      token_type: 'Bearer';
      /** @description HS256 JWT, 15-minute lifetime. */
      access_token: string;
      /**
       * Format: int64
       * @description Access-token lifetime in seconds.
       * @example 900
       */
      expires_in: number;
      /** @description Opaque, single-use; rotate via `/v1/auth/refresh`. */
      refresh_token: string;
      /**
       * Format: int64
       * @description Refresh-token lifetime in seconds.
       * @example 2592000
       */
      refresh_expires_in: number;
    };
    /** @description Login/verification result — the user and their tokens. */
    AuthSession: {
      user: components['schemas']['UserProfile'];
      tokens: components['schemas']['AuthTokens'];
    };
    /** @description Partial profile update — absent fields stay untouched. */
    UpdateProfileRequest: {
      display_name?: string;
      /** @enum {string} */
      locale?: 'fr' | 'mg';
    };
    /**
     * @description Kind of eatery (project book ch. 6.1).
     * @enum {string}
     */
    EstablishmentType:
      | 'restaurant'
      | 'gargotte'
      | 'cafe'
      | 'snack'
      | 'food_truck'
      | 'street_vendor'
      | 'pastry_shop'
      | 'bar_restaurant'
      | 'hotel_restaurant';
    /** @description WGS 84 coordinate (SRID 4326). */
    GeoPoint: {
      /**
       * Format: double
       * @example -18.9092
       */
      lat: number;
      /**
       * Format: double
       * @example 47.521
       */
      lng: number;
    };
    /** @description A referential entry with bilingual labels (FR + MG). */
    ReferentialItem: {
      /** @example mvola */
      code: string;
      /** @example MVola */
      label_fr: string;
      /** @example MVola */
      label_mg: string;
    };
    /** @description The one-query boolean attributes (project book ch. 4.3 / 6.1). */
    Amenities: {
      delivery: boolean;
      parking: boolean;
      wifi: boolean;
      wheelchair_access: boolean;
      air_conditioning: boolean;
      terrace: boolean;
      family_friendly: boolean;
      romantic: boolean;
      student_friendly: boolean;
      scenic_view: boolean;
      open_24h: boolean;
    };
    /** @description One opening interval; days are 0 = Monday … 6 = Sunday. */
    OpeningInterval: {
      day_of_week: number;
      /** @example 07:00 */
      opens_at: string;
      /** @example 21:00 */
      closes_at: string;
    };
    /** @description Aggregated ratings, recomputed nightly (project book ch. 4.5). Per-criterion and Bayesian fields are absent until an establishment has reviews. */
    RatingSummary: {
      /** @example 12 */
      count: number;
      /** @example 4.5 */
      avg_global?: number;
      avg_quality?: number;
      avg_price?: number;
      avg_cleanliness?: number;
      avg_speed?: number;
      avg_welcome?: number;
      /** @description Dampened score used for rankings. */
      bayesian_note?: number;
    };
    /** @description Card-level projection for lists and nearby results. */
    EstablishmentSummary: {
      /** Format: uuid */
      id: string;
      /** @example gargotte-chez-bao */
      slug: string;
      /** @example Gargotte Chez Bao */
      name: string;
      type: components['schemas']['EstablishmentType'];
      position: components['schemas']['GeoPoint'];
      /** @example 2500 */
      avg_price_ar?: number;
      verified: boolean;
      /** @enum {string} */
      status: 'active' | 'closed' | 'pending';
      /** @example 4.5 */
      rating_avg?: number;
      /** @example 12 */
      rating_count: number;
      /**
       * @description Metres from the query point; present only on `/v1/nearby`.
       * @example 30.5
       */
      distance_m?: number;
    };
    /** @description Full establishment detail (project book ch. 8.2 — detail page). */
    EstablishmentDetail: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
      type: components['schemas']['EstablishmentType'];
      position: components['schemas']['GeoPoint'];
      address?: string;
      /** @example Analakely */
      district?: string;
      /** @example Antananarivo */
      city: string;
      phone?: string;
      whatsapp?: string;
      facebook_url?: string;
      website?: string;
      avg_price_ar?: number;
      verified: boolean;
      /** @enum {string} */
      status: 'active' | 'closed' | 'pending';
      /** @description Computed server-side in Indian/Antananarivo. */
      open_now: boolean;
      amenities: components['schemas']['Amenities'];
      opening_hours: components['schemas']['OpeningInterval'][];
      payment_methods: components['schemas']['ReferentialItem'][];
      cuisines: components['schemas']['ReferentialItem'][];
      rating: components['schemas']['RatingSummary'];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @description A community proposal for a new establishment (book ch. 4.8). The position is the dropped pin; `city` defaults to Antananarivo. */
    EstablishmentProposal: {
      name: string;
      type: components['schemas']['EstablishmentType'];
      position: components['schemas']['GeoPoint'];
      address?: string;
      district?: string;
      /** @default Antananarivo */
      city: string;
      phone?: string;
      avg_price_ar?: number;
      /** @description Free note for the moderators (specialities, landmarks…). */
      comment?: string;
    };
    /** @description Acknowledgement that a contribution entered the moderation queue. */
    ContributionReceipt: {
      /**
       * Format: uuid
       * @description The contribution id, not an establishment id.
       */
      id: string;
      /** @enum {string} */
      status: 'pending';
      /** Format: date-time */
      created_at: string;
    };
    /** @description Partial business-profile update; absent fields stay untouched. Position and `verified` are not editable through this endpoint. */
    BusinessEstablishmentUpdate: {
      name?: string;
      address?: string;
      district?: string;
      phone?: string;
      whatsapp?: string;
      facebook_url?: string;
      website?: string;
      avg_price_ar?: number;
      /**
       * @description An owner can close or reopen, not self-approve out of `pending`.
       * @enum {string}
       */
      status?: 'active' | 'closed';
      amenities?: components['schemas']['AmenitiesUpdate'];
    };
    /** @description Partial amenities update — absent flags stay untouched. */
    AmenitiesUpdate: {
      delivery?: boolean;
      parking?: boolean;
      wifi?: boolean;
      wheelchair_access?: boolean;
      air_conditioning?: boolean;
      terrace?: boolean;
      family_friendly?: boolean;
      romantic?: boolean;
      student_friendly?: boolean;
      scenic_view?: boolean;
      open_24h?: boolean;
    };
    /** @description Full replacement of an establishment's opening intervals. */
    OpeningHoursUpdate: {
      intervals: components['schemas']['OpeningInterval'][];
    };
    /** @description A business account managing an establishment. */
    ManagerItem: {
      /** Format: uuid */
      user_id: string;
      /** @example Chez Bao */
      display_name: string;
      phone: components['schemas']['PhoneNumber'];
      /** Format: date-time */
      granted_at: string;
    };
    /** @description The managers of one establishment (no pagination). */
    ManagerPage: {
      items: components['schemas']['ManagerItem'][];
    };
    /** @description A published review (project book ch. 4.4). */
    ReviewItem: {
      /** Format: uuid */
      id: string;
      /** @example Naina */
      author_name: string;
      rating_quality: number;
      rating_price: number;
      rating_cleanliness: number;
      rating_speed: number;
      rating_welcome: number;
      /**
       * @description Weighted mean with quality counted twice (weights sum to 6).
       * @example 4.67
       */
      global_note: number;
      comment?: string;
      /** Format: date-time */
      created_at: string;
    };
    /** @description Payload to create a review. */
    ReviewInput: {
      rating_quality: number;
      rating_price: number;
      rating_cleanliness: number;
      rating_speed: number;
      rating_welcome: number;
      comment?: string;
    };
    /** @description A cursor-paginated page of establishment summaries. */
    EstablishmentPage: {
      items: components['schemas']['EstablishmentSummary'][];
      /** @description Pass back as `?cursor=`; absent on the last page. */
      next_cursor?: string;
    };
    /** @description What the deterministic smart-search rules (project book ch. 4.2) applied. Only present when at least one natural-language intent matched; values reflect the effective filters after explicit query parameters took precedence. */
    SearchInterpretation: {
      /** @description Matched intent identifiers (e.g. `hungry`, `cheap`, `breakfast`). */
      intents: string[];
      /** @description Present (true) when the query restricted to open establishments. */
      open_now?: boolean;
      /** @description Effective budget ceiling in ariary. */
      max_price_ar?: number;
      types?: components['schemas']['EstablishmentType'][];
      /** @description Boolean amenity filters switched on by the query. */
      amenities?: string[];
      /** @description Payment-method filter derived from the query (e.g. `mvola`, `mobile`). */
      payment?: string;
      /**
       * Format: double
       * @description Effective search radius, when a position was supplied.
       */
      radius_m?: number;
      /**
       * @description `discovery_score` for filter-only smart queries (Bayesian note + recent reviews + budget adequacy); `relevance` when text matching still applies.
       * @enum {string}
       */
      ordering: 'relevance' | 'discovery_score';
    };
    SearchPage: components['schemas']['EstablishmentPage'] & {
      interpretation?: components['schemas']['SearchInterpretation'];
    };
    /** @description One shareable thematic top (project book ch. 4.6). */
    RankingTopic: {
      /** @description Topic identifier, e.g. `top-rated` or `cuisine-malagasy`. */
      id: string;
      title_fr: string;
      title_mg: string;
    };
    RankingCatalog: {
      items: components['schemas']['RankingTopic'][];
    };
    /** @description A thematic top — at most 20 establishments, best first. */
    RankingPage: {
      topic: components['schemas']['RankingTopic'];
      items: components['schemas']['EstablishmentSummary'][];
    };
    /** @description A cursor-paginated page of reviews. */
    ReviewPage: {
      items: components['schemas']['ReviewItem'][];
      /** @description Pass back as `?cursor=`; absent on the last page. */
      next_cursor?: string;
    };
  };
  responses: {
    /** @description Invalid request. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Missing/invalid bearer token, or invalid credentials. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Authenticated but not allowed to perform this action. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Resource not found. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description The request conflicts with existing state. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Rate limit hit (e.g. 5 OTP codes/hour/number). */
    TooManyRequests: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    /** @description Page size (default 50 for establishments, 20 for reviews; max 100). */
    LimitParam: number;
    /** @description Opaque pagination cursor from a previous response's `next_cursor`. */
    CursorParam: string;
    /** @description Establishment UUID. */
    EstablishmentId: string;
    /** @description User account UUID. */
    UserId: string;
    /** @description Filter by establishment type. */
    TypeFilter: components['schemas']['EstablishmentType'];
    /** @description Minimum average price in ariary. */
    MinPriceFilter: number;
    /** @description Maximum average price in ariary (the budget king filter, book ch. 3). */
    MaxPriceFilter: number;
    /** @description Filter by cuisine referential code (e.g. `malagasy`, `grill`). */
    CuisineFilter: string;
    /** @description A payment-method code (e.g. `mvola`) or the literal `mobile` to match any mobile-money operator (book ch. 4.3). */
    PaymentFilter: string;
    /** @description Comma-separated boolean amenities that must all be true. One of: `delivery, parking, wifi, wheelchair_access, air_conditioning, terrace, family_friendly, romantic, student_friendly, scenic_view, open_24h`. */
    BooleanFilters: string;
    /** @description When true, keep only establishments open now (Indian/Antananarivo). */
    OpenNowFilter: boolean;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is up. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "service": "fikaliako-api",
           *       "message": "Aiza no hisakafo androany ?"
           *     }
           */
          'application/json': components['schemas']['PingResponse'];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Account created; verification code sent by SMS. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      400: components['responses']['BadRequest'];
      409: components['responses']['Conflict'];
    };
  };
  verifyPhone: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyPhoneRequest'];
      };
    };
    responses: {
      /** @description Phone verified; the account is now active. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      400: components['responses']['BadRequest'];
      403: components['responses']['Forbidden'];
    };
  };
  resendOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResendOtpRequest'];
      };
    };
    responses: {
      /** @description If the number has an unverified account, a code was sent. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      429: components['responses']['TooManyRequests'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Authenticated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  refreshTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description New token pair. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutRequest'];
      };
    };
    responses: {
      /** @description Session revoked (or the token was already unknown). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest'];
      };
    };
    responses: {
      /** @description If the number has an account, a reset code was sent. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      429: components['responses']['TooManyRequests'];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed; all sessions revoked. Log in again. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed; fresh tokens for this device. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  nearby: {
    parameters: {
      query: {
        lat: number;
        lng: number;
        /** @description Search radius in metres (default 1000, max 10000 — the 10 km distance tier of book ch. 4.2). */
        radius?: number;
        /** @description Filter by establishment type. */
        type?: components['parameters']['TypeFilter'];
        /** @description Minimum average price in ariary. */
        min_price?: components['parameters']['MinPriceFilter'];
        /** @description Maximum average price in ariary (the budget king filter, book ch. 3). */
        max_price?: components['parameters']['MaxPriceFilter'];
        /** @description Filter by cuisine referential code (e.g. `malagasy`, `grill`). */
        cuisine?: components['parameters']['CuisineFilter'];
        /** @description A payment-method code (e.g. `mvola`) or the literal `mobile` to match any mobile-money operator (book ch. 4.3). */
        payment?: components['parameters']['PaymentFilter'];
        /** @description Comma-separated boolean amenities that must all be true. One of: `delivery, parking, wifi, wheelchair_access, air_conditioning, terrace, family_friendly, romantic, student_friendly, scenic_view, open_24h`. */
        filters?: components['parameters']['BooleanFilters'];
        /** @description When true, keep only establishments open now (Indian/Antananarivo). */
        open_now?: components['parameters']['OpenNowFilter'];
        /** @description Max results (default 50, max 200 — the client clustering threshold). */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ordered nearby results. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentPage'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  search: {
    parameters: {
      query: {
        /** @description Free text — name, district, city, cuisine or dish (FR/MG). */
        q: string;
        /** @description Optional focus latitude; requires `lng`. */
        lat?: number;
        /** @description Optional focus longitude; requires `lat`. */
        lng?: number;
        /** @description Restrict to a radius in metres around (`lat`, `lng`); max 10000. */
        radius?: number;
        /** @description Filter by establishment type. */
        type?: components['parameters']['TypeFilter'];
        /** @description Minimum average price in ariary. */
        min_price?: components['parameters']['MinPriceFilter'];
        /** @description Maximum average price in ariary (the budget king filter, book ch. 3). */
        max_price?: components['parameters']['MaxPriceFilter'];
        /** @description Filter by cuisine referential code (e.g. `malagasy`, `grill`). */
        cuisine?: components['parameters']['CuisineFilter'];
        /** @description A payment-method code (e.g. `mvola`) or the literal `mobile` to match any mobile-money operator (book ch. 4.3). */
        payment?: components['parameters']['PaymentFilter'];
        /** @description Comma-separated boolean amenities that must all be true. One of: `delivery, parking, wifi, wheelchair_access, air_conditioning, terrace, family_friendly, romantic, student_friendly, scenic_view, open_24h`. */
        filters?: components['parameters']['BooleanFilters'];
        /** @description When true, keep only establishments open now (Indian/Antananarivo). */
        open_now?: components['parameters']['OpenNowFilter'];
        /** @description Page size (default 20, max 100). */
        limit?: number;
        /** @description Opaque pagination cursor from a previous response's `next_cursor`. */
        cursor?: components['parameters']['CursorParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Matching establishments, most relevant first. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchPage'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  listRankings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Available tops. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RankingCatalog'];
        };
      };
    };
  };
  getRanking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Topic identifier from the rankings catalog. */
        topicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The ranked establishments, best first. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RankingPage'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  listEstablishments: {
    parameters: {
      query?: {
        /** @description Filter by establishment type. */
        type?: components['parameters']['TypeFilter'];
        /** @description Minimum average price in ariary. */
        min_price?: components['parameters']['MinPriceFilter'];
        /** @description Maximum average price in ariary (the budget king filter, book ch. 3). */
        max_price?: components['parameters']['MaxPriceFilter'];
        /** @description Filter by cuisine referential code (e.g. `malagasy`, `grill`). */
        cuisine?: components['parameters']['CuisineFilter'];
        /** @description A payment-method code (e.g. `mvola`) or the literal `mobile` to match any mobile-money operator (book ch. 4.3). */
        payment?: components['parameters']['PaymentFilter'];
        /** @description Comma-separated boolean amenities that must all be true. One of: `delivery, parking, wifi, wheelchair_access, air_conditioning, terrace, family_friendly, romantic, student_friendly, scenic_view, open_24h`. */
        filters?: components['parameters']['BooleanFilters'];
        /** @description When true, keep only establishments open now (Indian/Antananarivo). */
        open_now?: components['parameters']['OpenNowFilter'];
        /** @description Page size (default 50 for establishments, 20 for reviews; max 100). */
        limit?: components['parameters']['LimitParam'];
        /** @description Opaque pagination cursor from a previous response's `next_cursor`. */
        cursor?: components['parameters']['CursorParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of establishments. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentPage'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  proposeEstablishment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstablishmentProposal'];
      };
    };
    responses: {
      /** @description Proposal accepted for moderation. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContributionReceipt'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  getEstablishment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The establishment UUID or its slug. */
        idOrSlug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The establishment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentDetail'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  listReviews: {
    parameters: {
      query?: {
        /** @description Page size (default 50 for establishments, 20 for reviews; max 100). */
        limit?: components['parameters']['LimitParam'];
        /** @description Opaque pagination cursor from a previous response's `next_cursor`. */
        cursor?: components['parameters']['CursorParam'];
      };
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of reviews. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewPage'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  createReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewInput'];
      };
    };
    responses: {
      /** @description Review created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewItem'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The authenticated user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  updateCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileRequest'];
      };
    };
    responses: {
      /** @description The updated profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  listFavorites: {
    parameters: {
      query?: {
        /** @description Page size (default 50 for establishments, 20 for reviews; max 100). */
        limit?: components['parameters']['LimitParam'];
        /** @description Opaque pagination cursor from a previous response's `next_cursor`. */
        cursor?: components['parameters']['CursorParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of favorited establishments. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentPage'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  addFavorite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Favorited (already-favorited is not an error). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  removeFavorite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Un-favorited (or was never favorited). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
    };
  };
  listManagedEstablishments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The managed establishments. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentPage'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  updateManagedEstablishment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BusinessEstablishmentUpdate'];
      };
    };
    responses: {
      /** @description The updated establishment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentDetail'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  replaceOpeningHours: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpeningHoursUpdate'];
      };
    };
    responses: {
      /** @description The establishment with its new hours. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EstablishmentDetail'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  listEstablishmentManagers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The accounts managing this establishment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManagerPage'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  grantEstablishmentManager: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
        /** @description User account UUID. */
        userId: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Granted (or already granted). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  revokeEstablishmentManager: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Establishment UUID. */
        establishmentId: components['parameters']['EstablishmentId'];
        /** @description User account UUID. */
        userId: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked (or was never granted). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
}
